server:
  port: 8082
  
spring:
  datasource:
   url: jdbc:mysql://localhost:3306/hospitaldb
   password: root
   username: root
   driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
   hibernate:
      ddl-auto: update
   show-sql: true 
   database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
   
  application:
    name: HOSPITAL-SERVICE

  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      
eureka:
  instance:
    prefer-ip-address: true   

zipkin:
  base-url: http://localhost:9411/
  
resilience4j.circuitbreaker:
  configs:
    default:
      registerHealthIndicator: true
      ringBufferSizeInClosedState: 4
      ringBufferSizeInHalfOpenState: 2
      automaticTransitionFromOpenToHalfOpenEnabled: true
      waitDurationInOpenState: 20s
      failureRateThreshold: 50
      eventConsumerBufferSize: 10
      ignoreExceptions:
      recordExceptions:
        - java.net.SocketTimeoutException
        - java.net.ConnectException
        